# Source: acme/templates/cert-manager-prod-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    meta.helm.sh/release-name: 'acme-jx'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "uaemmx@gmail.com"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsNames:
            - "*.dev.jenkinsxlab.com"
            - "dev.jenkinsxlab.com"
        # ACME DNS-01 provider configurations
        dns01:
          cloudDNS:
            # The project in which to update the DNS zone
            project: "sandbox-devops-345305"
