# Source: external-dns/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: "jx"
  labels:
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-6.4.5
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    iam.gke.io/gcp-service-account: tf-jx-wired-krill-dn@sandbox-devops-345305.iam.gserviceaccount.com
    meta.helm.sh/release-name: 'external-dns'
automountServiceAccountToken: true
